type User {
    id: ID!
    email: String!
    name: String!
    posts: [Post!]!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type Post {
    id: ID!
    title: String!
    content: String!
    createdAt: DateTime!
    updatedAt: DateTime!
    author: User!
    authorId: ID!
}

type AuthPayload {
    token: String!
    user: User!
}

type Query {
    me: User
    posts: [Post!]!
}

type Mutation {
    signup(email: String!, name: String!, password: String!): AuthPayload!
    login(email: String!, password: String!): AuthPayload!
    createPost(title: String!, content: String!): Post!
}

scalar DateTime
